version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: challenge_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./Challenge.Api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./Challenge.Api/appsettings.Development.json:/app/appsettings.Development.json:ro
      - ./Challenge.Api/appsettings.json:/app/appsettings.json:ro
    ports:
      - "5000:80"
    restart: unless-stopped

volumes:
  db_data:
